<%@ Page Language="C#" Inherits="System.Web.Mvc.ViewPage"%><%=Request.QueryString.Get("callback")%>([
{"id":"101","text":"部门管理","cls":"forum-ct","iconCls":"forum-parent","expanded":true,
"children":[
{"id":"102","text":"部门管理","cls":"forum","iconCls":"icon-forum","url":62594,"leaf":true},
{"id":"103","text":"部门分配权限","cls":"forum","iconCls":"icon-forum","url":62594,"leaf":true}
]},
{"id":"121","text":"用户管理","cls":"forum-ct","iconCls":"forum-parent","expanded":true,
"children":[
{"id":"122","text":"用户管理","cls":"forum","iconCls":"icon-forum","url":"/user/list","leaf":true},
{"id":"123","text":"用户分配角色","cls":"forum","iconCls":"icon-forum","url":"/user/role","leaf":true}
]},
{"id":"141","text":"角色管理","cls":"forum-ct","iconCls":"forum-parent","expanded":true,
"children":[
{"id":"142","text":"角色管理","cls":"forum","iconCls":"icon-forum","url":"/Manager/userrole/tree","leaf":true},
{"id":"143","text":"角色分配权限组","cls":"forum","iconCls":"icon-forum","url":"/Manager/userRole/actionGroup","leaf":true},
{"id":"144","text":"角色分配权限","cls":"forum","iconCls":"icon-forum","url":"/Manager/userRole/action","leaf":true},
{"id":"145","text":"角色分配菜单","cls":"forum","iconCls":"icon-forum","url":"/Manager/userRole/menu","leaf":true}
]},
{"id":"151","text":"功能组管理","cls":"forum-ct","iconCls":"forum-parent","expanded":true,
"children":[
{"id":"152","text":"功能组管理","cls":"forum","iconCls":"icon-forum","url":"/Manager/PActionGroup/List","leaf":true}
]},
{"id":"161","text":"功能管理","cls":"forum-ct","iconCls":"forum-parent","expanded":true,
"children":[
{"id":"162","text":"功能管理","cls":"forum","iconCls":"icon-forum","url":"/Manager/PAction/List","leaf":true}
]},
{"id":"181","text":"菜单管理","cls":"forum-ct","iconCls":"forum-parent","expanded":true,
"children":[
{"id":"182","text":"菜单管理","cls":"forum","iconCls":"icon-forum","url":"/Manager/PMenu/Tree","leaf":true}
]},
{"id":"191","text":"缓存管理","cls":"forum-ct","iconCls":"forum-parent","expanded":true,
"children":[
{"id":"192","text":"缓存管理","cls":"forum","iconCls":"icon-forum","url":"/Manager/System/List","leaf":true}
]},
{"id":"171","text":"日志管理","cls":"forum-ct","iconCls":"forum-parent","expanded":true,
"children":[
{"id":"172","text":"日志管理","cls":"forum","iconCls":"icon-forum","url":62594,"leaf":true}
]}
]);
<%Response.ContentType = "text/html";Response.HeaderEncoding=Encoding.UTF8;%>