//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Com.Zfrong.Common.DotnetSkin
{
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DotNetSkinRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DotNetSkinRes() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsApplication1.DotNetSkinRes", typeof(DotNetSkinRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static byte[] MacOS_BLUE {
            get {
                object obj = ResourceManager.GetObject("MacOS_BLUE", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] MacOS_TGRB2 {
            get {
                object obj = ResourceManager.GetObject("MacOS_TGRB2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Office2007 {
            get {
                object obj = ResourceManager.GetObject("Office2007", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Royale_INDIGOT {
            get {
                object obj = ResourceManager.GetObject("Royale_INDIGOT", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] VISTAXPB2 {
            get {
                object obj = ResourceManager.GetObject("VISTAXPB2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Wmpx_XMP2 {
            get {
                object obj = ResourceManager.GetObject("Wmpx_XMP2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] XP_BLUE {
            get {
                object obj = ResourceManager.GetObject("XP_BLUE", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] XP_HOMESTEAD {
            get {
                object obj = ResourceManager.GetObject("XP_HOMESTEAD", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] XP_METALLIC {
            get {
                object obj = ResourceManager.GetObject("XP_METALLIC", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
